name: ASMR_cuda

channels:
  - default
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.9
  - numpy=1.22.3
  - wandb=0.14.2
  - tqdm=4.63.0
  - plotly=5.6
  - scikit-learn=1.0.2
  - gym=0.21.0
  - stable-baselines3=1.1.0
  - shapely=1.8.2
  - meshio=5.3.4
  - numba=0.56.4
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pip=22.0.4
  - pip:
      - -r ./requirements-cuda.txt
# need to install cw2 and optunawork afterwards using the pip requirements.txt

# pytorch related installs may not work on windows. These include pytorch, pyg and stable-baselines3.
# see e.g., https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html
# pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cpu.html
# pip install stable-baselines3
