# mesh refinement experiments for the cluster

name: "SLURM"   # MUST BE "SLURM"

# Required
partition: "single"
job-name: "heat_diffusion"    # this will be the experiments name in slurm
num_parallel_jobs: 30  # to prevent wandb overload
time: 4320  # in minutes
ntasks: 1
cpus-per-task: 16
mem-per-cpu: 8000

---

name: "DEFAULT"   # MUST BE DEFAULT
import_path: "asmr_default.yaml"
params:
  task:
    mesh_refinement:
      fem:
        heat_diffusion:
          diffusivity: 0.001
        domain:
          domain_type: convex_polygon
          maximum_distortion: 0.2
        pde_type: heat_diffusion
      evaluation:
        # we only use 1 evaluation environment here because computing a new reference mesh for each evaluation step
        # is relatively costly
        fem:
          num_pdes: 1
          domain:
            fixed_domain: True
            maximum_distortion: 0.0
          heat_diffusion:
            fixed_diffusion: True


---
# this experiment is a list of 4 different methods that use a scaled area reward formulation
name: heat_diffusion_asmr
params:
  algorithm:
    use_mixed_reward: True
list:
  recording:
    nametag: [ "asmr" ]
    idx: [ 0 ]  # give a number to the experiments for easier comparison in the pareto plots
grid:
  task:
    mesh_refinement:
      element_penalty: [ 0.3, 0.1, 0.075, 0.05, 0.03,
                         0.01, 0.0075, 0.006, 0.005, 0.003 ]

---
name: heat_diffusion_argmax
params:
  algorithm:
    ppo:
      value_function_scope: graph
    dqn:
      max_replay_buffer_size: 10000
  task:
    mesh_refinement:
      refinement_strategy: argmax  # refine exactly 1 element in every step as described in the argmax paper
      element_penalty: 0.0  # no face penalty since we refine exactly 1 element in every step in any case
      reward_type: argmax  # reward type of the original baseline paper. No need to do area comparisons here
      num_timesteps: 100  # give enough steps to make a nice refinement

list:
  recording:
    nametag: [ argmax_dqn ]
    idx: [ 11 ]
  algorithm:
    name: [ argmax_dqn ]
grid:
  task:
    mesh_refinement:
      num_timesteps: [ 25, 50, 75, 100, 150,
                       200, 250, 300, 350, 400 ]

---

name: heat_diffusion_vdgn

params:
  task:
    mesh_refinement:
      reward_type: vdgn
  algorithm:
    name: ppo  # vdgn-ppo is a version of ppo with global rewards (as returned by the "vdgn" reward type) and a value
      # decomposition, which is given by the "value_function_scope"="spatial".

list:
  recording:
    nametag: [ "vdgn_ppo" ]  # [ "vdgn_ppo", "vdgn_dqn" ]
    idx: [ 12 ]
grid:
  task:
    mesh_refinement:
      element_penalty: [ 5.0e-3, 2.0e-3, 1.0e-3, 5.0e-4, 2.0e-4,
                         1.0e-4, 5.0e-5, 2.0e-5, 1.0e-5, 5.0e-6, ]

---
name: heat_diffusion_sweep

params:
  task:
    environment_class: sweep_mesh_refinement
    mesh_refinement:
      element_penalty: 25
      num_training_timesteps: 200 # use different episode lengths for single agent training & multi-agent evaluation
      # here, we use 512 steps to give the agent enough time to learn the task
      num_evaluation_timesteps: 6
      reward_type: sweep  # use the sweep reward

      element_features: # Sweep exclusive features.
        resource_budget: True # current number of elements / maximum number of elements
        average_solution: True
        mean_area_neighbors: True # Agent gets mean area of neighbor elements
        mean_edge_attributes: True # Mean
      include_globals: False # not used for this method, as global information is in the element features
  algorithm:
    network:
      type_of_base: sweep

    name: sweep_ppo
    ppo:
      value_function_scope: graph
      num_rollout_steps: 512
    dqn:
      steps_per_iteration: 96
      max_replay_buffer_size: 10000

list:
  recording:
    nametag: [ "sweep_ppo" ]
    idx: [ 14 ]
grid:
  task:
    mesh_refinement:
      maximum_elements: [ 400, 500, 750, 1000, 1500,
                          2000, 2500, 3000, 4000, 5000 ]

---
name: heat_diffusion_maximum_reward
# using a maximum as the reward
params:
  task:
    mesh_refinement:
      fem:
        error_metric: maximum
      reward_type: spatial_max
  algorithm:
    use_mixed_reward: True
list:
  recording:
    nametag: [ "max_reward" ]
    idx: [ 21 ]
grid:
  task:
    mesh_refinement:
      element_penalty: [ 5.0e-2, 1.0e-2, 7.5e-3, 5.0e-3, 4.0e-3,
                         2.0e-3, 1.0e-3, 5.0e-4, 2.0e-4, 1.0e-4]
---
name: heat_diffusion_no_area
# experiments without the area-scaling in the reward

list:
  recording:
    nametag: [ "no_area_spatial", "no_area_global" ]
    idx: [ 22,23]  # give a number to the experiments for easier comparison in the pareto plots
  task:
    mesh_refinement:
      reward_type: [ spatial, spatial ]
  algorithm:
    ppo:
      value_function_scope: [ spatial, graph ]
    curriculum:
      max_global_weight: [ 0.5, 0.0 ]
grid:
  task:
    mesh_refinement:
      element_penalty:
        value: [ 5.0e-4, 2.0e-4, 1.0e-4, 5.0e-5, 2.0e-5,
                 1.0e-5, 5.0e-6, 2.0e-6, 1.0e-6, 5.0e-7 ]
---
name: heat_diffusion_no_area_global
# experiments with the area-scaling and a global value function scope

params:
  task:
    mesh_refinement:
      reward_type: spatial_area
  algorithm:
    ppo:
      value_function_scope: graph
    curriculum:
      max_global_weight: 0.0
list:
  recording:
    nametag: [ "global" ]
    idx: [ 24 ]  # give a number to the experiments for easier comparison in the pareto plots

grid:
  task:
    mesh_refinement:
      element_penalty:
        value: [ 0.1, 0.075, 0.05, 0.03, 0.01,
                 0.0075, 0.006, 0.005, 0.003, 0.001 ]

---
name: heat_diffusion_oracle_heuristic
repetitions: 1
reps_per_job: 1
reps_in_parallel: 1
iterations: 1

---
name: heat_diffusion_oracle_maxheuristic
repetitions: 1
reps_per_job: 1
reps_in_parallel: 1
iterations: 1

params:
  task:
    mesh_refinement:
      fem:
        error_metric: maximum
---
name: heat_diffusion_uniform_mesh
repetitions: 1
reps_per_job: 1
reps_in_parallel: 1
iterations: 1
params:
  task:
    mesh_refinement:
      maximum_elements: 100000
